module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#FF6B00',
        'primary-dark': '#E55A00',
        secondary: '#22C55E',
        danger: '#EF4444',
        warning: '#F59E0B',

        'surface-light': '#FFFFFF',
        'surface-dark': '#1A1A1A',
        'background-light': '#F5F5F5',
        'background-dark': '#0D0D0D',
        'text-primary-light': '#1A1A1A',
        'text-primary-dark': '#FFFFFF',
        'text-secondary-light': '#6B7280',
        'text-secondary-dark': '#9CA3AF',
        'border-light': '#E5E5E5',
        'border-dark': '#374151',
      },
      fontFamily: {
        sans: ['Inter-Regular', 'sans-serif'],
        'inter-bold': ['Inter-Bold', 'sans-serif'],
        'inter-semibold': ['Inter-SemiBold', 'sans-serif'],
        'inter-medium': ['Inter-Medium', 'sans-serif'],
      },
      fontSize: {
        'h1': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'h2': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'h3': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-bold': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'caption': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'small': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'button': ['16px', { lineHeight: '24px', fontWeight: '700' }],
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        '2xl': '48px',
      },
      borderRadius: {
        'sm': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '24px',
      },
    },
  },
  plugins: [],
};
